### ISSUE TITLE
Combined KM Plot and tables for faceting

### ISSUE THREAD

**Issue by cschaerfe** [openpharma/visR#14]
When stratifying, it is sometimes useful to use ggplot's faceting (`facet_grid` and `facet_wrap`) However, this only works (if at all) only for the KM plot (e.g., when using survminer, but also visR), but it would be really useful to also have the risk table for each facet. 
Maybe this is something we could implement in the future?

**Comment by SHAESEN2** [comment]
Did you look at the Survminer examples? 

`
# Arrange faceted survival curves and risk tables
g2 <- ggplotGrob(curv_facet)
g3 <- ggplotGrob(tbl_facet)
min_ncol <- min(ncol(g2), ncol(g3))
g <- gridExtra::gtable_rbind(g2[, 1:min_ncol], g3[, 1:min_ncol], size="last")
g$widths <- grid::unit.pmax(g2$widths, g3$widths)
grid::grid.newpage()
grid::grid.draw(g)
`

Note that one typo was present in the original code.
