### ISSUE TITLE
grid parameter from define_theme() function dosen't update a plot

### ISSUE THREAD

**Issue by lesniewa** [openpharma/visR#188]
#### Issue description
I would like to render a graph with a grid and white background (instead of default gray). My understating was that it should feasible to achieve by a combination of `grid` and `bg` parameters from `define_theme()`. However, passing TRUE and FALSE values in the `grid` parameter generate the same result.

#### Steps to reproduce the issue
```r
lung_cohort <- survival::lung

lung_cohort <- lung_cohort %>%  
  dplyr::mutate(sex = as.factor(ifelse(sex == 1, "Male", "Female")))  %>%  
  dplyr::rename(Age = "age", Sex = "sex", Status = "status", Days = "time")

# Select variables of interest and change names to look nicer
lung_cohort_survival <- lung_cohort %>%  
  dplyr::select(Age, Sex, Status, Days)  

# For the survival estimate, the censor must be 0 or 1
lung_cohort_survival$Status <- lung_cohort_survival$Status - 1

# Estimate the survival curve
lung_suvival_object <- lung_cohort_survival %>% 
  visR::estimate_KM(strata = "Sex", CNSR = "Status", AVAL = "Days")

gg <- visR::visr(lung_suvival_object,
                 y_label = "Survival probability",
                 x_label = "Time (years)",
                 x_units = NULL,
                 x_ticks = NULL,
                 y_ticks = NULL,
                 fun = "surv",
                 legend_position = "top",
                 box_width = 50,
                 font_size = 50,
                 fill = "white",
                 border = "white")

theme <- visR::define_theme(fontsizes = list("axis" = 15,
                                             "ticks" = 15),
                            fontfamily = "Helvetica",
                            grid = TRUE,
                            bg = "white")
gg  %>% visR::add_theme(theme)
```

#### What's the expected result?
Plot with a white background and with a grid.

#### What's the actual result?
Plot with a white background, but without a grid.

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/84186593/119646394-656f7900-be1f-11eb-9238-38da46bd7c8a.png)

**Comment by timtreis** [comment]
Hey lesniewa, thanks for identifying that error! We dealt with the issue (and also included your suggestion from the other issue) in a PR that will probably be merged later this week. I'll ping you afterwards again to give you an update. Cheers!
