### ISSUE TITLE
Readme contribution plot is broken on gh actions

### ISSUE THREAD

**Issue by epijim** [openpharma/visR#209]
#### Issue description

![image](https://user-images.githubusercontent.com/2760096/120709893-bb968900-c4bd-11eb-8600-1437d8284e79.png)

trying to figure why we get above via CICD in the branch fixreadme

**Comment by SHAESEN2** [comment]
Could you try to prefix all the function calls? eg local_repo <- gitsum::parse_log_detailed() 
It might be that there is masking of the functions that you actually need. By prefixing, you ensure the correct functions are used. We have had this issue before.

**Comment by bailliem** [comment]
Closed with ci/cd update
