### ISSUE TITLE
In the absence of a specified x-label or a data-derived label, should the x-axis be blank?

### ISSUE THREAD

**Issue by timtreis** [openpharma/visR#213]
See title.

Related to the comments in PR https://github.com/openpharma/visR/pull/211 and https://github.com/openpharma/visR/pull/212.

**Comment by SHAESEN2** [comment]
Hey Tim. We discussed that this should be blank. Did you manage to make the updates?

**Comment by timtreis** [comment]
Didn't work on it yet, but it's on my list :+1: I'll also have to rewrite a bunch of the tests, so I wanted to do it all in one go
