### ISSUE TITLE
CRAN: installed.packages() can be very slow, try not to use it

### ISSUE THREAD

**Issue by timtreis** [openpharma/visR#220]
You are using installed.packages():
"This needs to read several files per installed package, which will be
slow on Windows and on some network-mounted file systems.
It will be slow when thousands of packages are installed, so do not use
it to find out if a named package is installed (use find.package or
system.file) nor to find out if a package is usable (call
requireNamespace or require and check the return value) nor to find
details of a small number of packages (use packageDescription)."
[installed.packages() help page]

**Comment by bailliem** [comment]
closed with pr #221
