### ISSUE TITLE
Add in the packages score on a risk metric

### ISSUE THREAD

**Issue by epijim** [openpharma/visR#232]
## Idea

Could we track the 'trust worthiness' of the package as a badge? e.g.  calculate risk metric score and show it as a badge? 

## Steps

Add riskmetric to cicd - and expose as badge (if no badge service exists I guess could just write a svg via the gh action).

## Concern

Is the score designed to be used on a single package? e.g. what does '0.8' mean to an end user?

It's also easy for us to game the number by looking at the categories - although maybe that also increases the quality of the package so is ok?

**Comment by timtreis** [comment]
We'll then definitely have to consider how we indicate that "low is good". Since "risk score" might be ambiguous, no?

**Comment by SHAESEN2** [comment]
There is an issue for this: https://github.com/pharmaR/riskmetric/issues/189

**Comment by dgkf** [comment]
Hi - reaching out from the [riskmetric](https://github.com/pharmaR/riskmetric) team and the R Validation Hub more broadly

We would love to provide an easy way of building/serving badges, and have just lacked developer time so far to get it off the ground. We would welcome the contribution!

For now, it would be easy enough to embed the score in a shields API call. Wrapping that up into a little helper function should be pretty do-able. For example:

`https://img.shields.io/badge/riskmetric-0.12-green` 
<img src=https://img.shields.io/badge/riskmetric-0.12-green></img>

It would also be great to get your feedback on whether you think the score reflects the trustworthiness of visR - there's a lot of active discussion on how to better reflect package quality, and it would be awesome to start getting more active real-world feedback.

**Comment by SHAESEN2** [comment]
Thank you @dgkf to reach out. I have been trying to get riskmetric to run to evaluate risk, but it is very slow. The app crashes when I upload an excel file. I need to figure out what is going on first. Perhaps @epijim  @timtreis  can give it a go on their system.
