### ISSUE TITLE
Stratifier inside of tableone call leads to NAs, should be automatically removed

### ISSUE THREAD

**Issue by timtreis** [openpharma/visR#254]
#### Issue description

A naive 'tableone()` call leads to NAs being introduced into the rendered table.

```
tableone(data, strata = "Sex", 
         title = TITLE, datasource = DATASOURCE)
```
![Screenshot_20210910_112934](https://user-images.githubusercontent.com/12818242/132832837-019601a6-15c5-486e-8183-6d0ff1c72b12.png)

Therefore the strata needs to be manually removed before rendering the table.

```
get_tableone(data, strata = "Sex") %>% 
  filter(variable != "Sex") %>% 
  render(title = TITLE, datasource = DATASOURCE)
```

This should be done automatically.

**Comment by rebecca-albrecht** [comment]
Actually I just realized that the stratifier is not included when we set the parameter `overall` to `F`. I seems that the stratifier is only in there because of the `Total` column. So maybe this is even what we want?

**Comment by timtreis** [comment]
Implement `na.action` for removal of stratifier that leads to NAs
