### ISSUE TITLE
Set up CI/CD workflow

### ISSUE THREAD

**Issue by bailliem** [openpharma/visR#26]
Post webinar set up a CI/CD workflow including
* unit tests
* dependencies 
* styling and linting
* documentation build
* website build

**Comment by kawap** [comment]
I could take this task and prepare CI/CD workflow in Travis .. but I am wondering if this possible to use Travis CI in Roche-phcaa for usage with github, not github.roche?

**Comment by bailliem** [comment]
That would be great if you were happy to look in to it. If there was a workflow that could allow this to work with cross organisation collaboration, etc.
