### ISSUE TITLE
get_pvalue gives too many digits

### ISSUE THREAD

**Issue by timtreis** [openpharma/visR#262]
#### Steps to reproduce the issue

As pointed out during Charlottas talk at PSI2021, the `get_pvalue()` function doesn't round the Chisq values by default. This should have a default precision

```r
library(visR)

adtte %>%
  estimate_KM("SEX") %>%
  get_pvalue()

#   Equality across strata      Chisq        df        p-value
#   Log-Rank                    3.739420     1           0.053
#   Wilcoxon                    4.603920     1           0.032
#   Tarone-Ware                 4.643328     1           0.031

```

#### What's the expected result?

Same precision as for p-value

**Comment by SHAESEN2** [comment]
Close with #265
