### ISSUE TITLE
Kaplan-Meier Plot - add_risktable is failing when strata is NULL 

### ISSUE THREAD

**Issue by prabhushanmup** [openpharma/visR#282]
#### Issue description
Trying to generate Kaplan-Meier plot without strata variable.
Expectation is when `strata is NULL` in `estimate_KM` still risk table has to be showed considering for ALL records.
But function `add_risktable` is failing when `strata is NULL` in `estimate_KM`

Same behavior observed when strata column has 1 group only. consider `column SAFFL` has 1 group (Y) only

#### Steps to reproduce the issue
2 examples are provided
1. when strata is NULL
2. when strata column has 1 group only

```r
adtte %>%
    estimate_KM(strata = NULL, conf.int = 0.90) %>%
    visr(legend_position = "right", x_unit = "Days") %>%
    add_CI(style = "ribbon") %>%
    add_CNSR(shape = 3, size = 1) %>%
    add_risktable(
        statlist = c("n.risk", "n.event", "n.censor"),
        label = c("At risk", "Event", "Censor")
    )
```

```r
adtte %>%
    estimate_KM(strata = "SAFFL", conf.int = 0.90) %>%
    visr(legend_position = "right", x_unit = "Days") %>%
    add_CI(style = "ribbon") %>%
    add_CNSR(shape = 3, size = 1) %>%
    add_risktable(
        statlist = c("n.risk", "n.event", "n.censor"),
        label = c("At risk", "Event", "Censor")
    )
```

#### What's the expected result?
Risk table to be showed in the plot
-

#### What's the actual result?
```
Error in data.frame(time = survfit_summary$time, strata = base::factor(.get_strata(survfit_summary[["strata"]]),  : 
  arguments imply differing number of rows: 11, 0
```
-

#### Additional details / screenshot
please generate similar to this 

![image](https://user-images.githubusercontent.com/69159004/137876377-021ad1a6-c203-4f13-af2e-8a295373e9e3.png)

**Comment by prabhushanmup** [comment]
Hi @timtreis 
Looks the issue still exists
Could you please help me to get this work 
```
devtools::install_github("openpharma/visR", ref = "develop")
library(visR)
adtte %>%
    estimate_KM(strata = NULL, conf.int = 0.90) %>%
    visr(legend_position = "right", x_unit = "Days") %>%
    add_CI(style = "ribbon") %>%
    add_CNSR(shape = 3, size = 1) %>%
    add_risktable(
        statlist = c("n.risk", "n.event", "n.censor"),
        label = c("At risk", "Event", "Censor")
    )```

Error in data.frame(time = survfit_summary$time, strata = base::factor(base::sub(".*=",  : 
  arguments imply differing number of rows: 11, 0

**Comment by timtreis** [comment]
Hey @prabhushanmup, absolutely! I'll check later today :)

**Comment by timtreis** [comment]
@prabhushanmup Your exact code works on my machine. Did you try to uninstall visR before querying from GitHub?

**Comment by prabhushanmup** [comment]
Hi @timtreis 
Perfectly working. Thanks for your support.
Please close this issue.
