### ISSUE TITLE
get_pvalue fails when survfit_object is calculated without strata

### ISSUE THREAD

**Issue by prabhushanmup** [openpharma/visR#287]
#### Issue description
visR::get_pvalue is throwing error when survfit_object is calculated without strata argument

Error in visR::get_pvalue(survfit_object) : 
  Main effect has only 1 level. Test of equality over strata can't be determined.

#### Steps to reproduce the issue

Please share code if possible.

```r
survfit_object <- visR::estimate_KM(data = adtte)
visR::get_pvalue(survfit_object)
```

#### What's the expected result?
p value
-

#### What's the actual result?
Error in visR::get_pvalue(survfit_object) : 
  Main effect has only 1 level. Test of equality over strata can't be determined.
-

**Comment by SHAESEN2** [comment]
The Null hypothesis of the get_pvalue is that there is no difference in survival between **two or more** independent groups. This testing hypothesis does not make sense for only one group as there is nothing to compare with.
