### ISSUE TITLE
Feature Request: Cumulative Incidence Plots for Competing Risks Data

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#293]
Hello! The visR project is amazing! Thank you for all your work 

I love the plots you've created for Kaplan-Meier estimates with the risk tables. They're beautiful. I am working on a package at the moment to modernize the API of working with competing risks data, and as a part of that, export proper tidying methods for cumulative incidence. https://mskcc-epi-bio.github.io/tidycmprsk/

We have a simple `autoplot()` method for visualizing the estimates, but no way of adding risk tables below the figure.
https://mskcc-epi-bio.github.io/tidycmprsk/reference/autoplot.tidycuminc.html
![image](https://user-images.githubusercontent.com/26774684/145608683-3170dcbb-b771-40a8-98e5-44566121d799.png)

Couple of questions: 
1. Would you be amenable to a PR that would provide support for competing risks endpoints? I think the API would be similar to your KM estimates methods.
```r
data %>%
  estimate_CUMINC(strata = "TRTP", conf.int = 0.90) %>%
  visr(legend_position = "right", x_unit = "Days") %>%
  add_CI(style = "ribbon") %>%
  add_CNSR(shape = 3, size = 1) %>%
  add_risktable(
    statlist = c("n.risk", "n.event", "n.censor"),
    label = c("At risk", "Event", "Censor")
  )
```

2. If you would prefer not to support competing risks, could I have a brief chat with you about the methods you used to get the risk tables on your figures and I can try to implement something similar within my package?

Thank you!
Daniel

**Comment by SHAESEN2** [comment]
Hey @ddsjoberg We would love to incorporate competing risks. Please let us know what you need from us to get the PR into our package. Do you think we could extend our estimate_KM parameters to allow for competing risks? This would mean we could leverage our framework easier.

**Comment by ddsjoberg** [comment]
@SHAESEN2 great! I'll start putting something together.

**Comment by ddsjoberg** [comment]
Hey hey @SHAESEN2 !

I put something together today in this fork/branch
https://github.com/ddsjoberg/visR/tree/cmprsk

There is still quite a bit to do before it could be merged. But I wanted to chat about a few things before working on it more. What's the best way for your workflow? Should I open draft pull request and we can chat about specific lines? Do you prefer the conversation to be entirely in the issue?

**Comment by SHAESEN2** [comment]
Hey,

I took a quick glance and it looks quite good. Do you need help to write a few tests for the updates? We can have a call for sure. Do you want to attend our weekly meeting Thursday at 13:30 CET or do you prefer to have a separate chat? Happy to set something up if you let me know your availability.

**Comment by ddsjoberg** [comment]
thanks @SHAESEN2 ! I'll message you on the Slack channel to setup a time to chat. I'll also update this issue ahead of our chat with items for discussion.
