### ISSUE TITLE
Examples and test-files use visR:: notation, can probably be skipped.

### ISSUE THREAD

**Issue by timtreis** [openpharma/visR#300]
@SHAESEN2 do you have the technical suggestion of Daniel here?

**Comment by SHAESEN2** [comment]
Daniel proposed to remove the visR:: (prefix) in all examples and test files because it will clash with users that use 'load all' in their workflow. I remember that R will then look for the properly installed visR instead of the rebuild package that you are developping.

**Comment by SHAESEN2** [comment]
Hey @timtreis I think I understand the issue. It is to support lazy/quick development so you dont have to rebuild the package every time. I think I prefer to keep prefix so we have maximal traceability. What do you think?

**Comment by timtreis** [comment]
I came to the advanced side of R from doing transcriptomics in bioconductor where every second package reimplements all dplyr verbs, so I'm definitely pro-prefix :D

**Comment by bailliem** [comment]
I agree. For now I would prefer to have the prefix, but also happy to revisit it later when the package matures
