### ISSUE TITLE
Package level documentation

### ISSUE THREAD

**Issue by SHAESEN2** [openpharma/visR#303]
Proposal to include package level metadata so we can use ?visR to render the package documentation. This file can also contain general imports such as @import From rlang .data .env

**Comment by SHAESEN2** [comment]
If you run usethis::use_package_doc(), it'll create a package-level documentation file using information from DESCRIPTION. It's roxygen2 comments are also a great place to consolidate all function imports from other packages.

**Comment by ddsjoberg** [comment]
This was added in #298 FYI
