### ISSUE TITLE
tidyme.survfit ( call ) and dependent friends

### ISSUE THREAD

**Issue by SHAESEN2** [openpharma/visR#304]
Daniel proposed to attach the survfit object to the estimated object rather than saving the call inside the dataframe because it might cause issues when users want to use this call and are not working in the associated environment. Another solution is to work with quosures.

**Comment by SHAESEN2** [comment]
We wanted to have the call to update it for get_cox_PH.
The reason for the_lhs() to get traceability inside the call back when using purrr or %>%

![image](https://user-images.githubusercontent.com/47894155/151693783-07ea5ff9-6e73-4caf-a467-5b198aa3e589.png)

Do you know a better way of keeping traceability?

**Comment by ddsjoberg** [comment]
I think the only issue is that the environment can become lost and the call will no longer be executable. For example, if a user wraps `estimate_KM()` in a user-defined function, e.g.

```r
my_custom_wrapper <- function(data, ...) {
  estimate_KM(data = data, ...)
}
```

When the traceback is constructed here, R will be looking for a data frame named `data` that only exists within this function. I find that users will often use your package in unexpected ways!

I see two ways around it
1. Add the `estimate_KM()` input arguments as a list to the returned `survfit()` objects, e.g.
    ```r
    estimate_KM <- function(data, CNSR, AVAL) {
       survfit_obj <- survival::survfit(...)
       survfit_obj$inputs  <- list(data = data, CNSR = CNSR, AVAL = AVAL) 
       survfit_obj
    } 
    ```
    This is the easier solution, and you can always reconstruct any survival object you may need using the inputs.
2. The other way to handle this is with precise handling of the evaluating environment, meaning the env is saved with the output. Whenever you need to evaluate any items from the `survfit()` call, you specify the precise environment in which they are to be evaluated. The rlang quosures can help make this process a bit easier than the base methods.

**Comment by ddsjoberg** [comment]
Anyway, the code already in the pkg is great and won't be an issue for the vast majority of users! 💯
