### ISSUE TITLE
Use a step ribbon plot for survival confidence intervals

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#319]
## Idea

**What is your idea for a new plot/table?**

The survival function is a step function, but the ribbon used for the 95% CI is not (it does a linear connect the dots). We could update the ribbon to use a function like this: https://adibender.github.io/pammtools/reference/geom_stepribbon.html

**Do you have any examples you can share of what it looks like?**
stepribbon vs regular ribbon

![image](https://user-images.githubusercontent.com/26774684/155216925-416a65c4-b2f1-48c5-8d70-c044ceb0c872.png)

**Are you interested to implement this yourself?**

I could, but can't provide a timeframe at the moment.

**Comment by timtreis** [comment]
I definitely see the rational and benefit behind this, but would be against adding the dependency just for this. If we'd want to switch to this more accurate representation, I'd argue in favour of reimplementing it.

**Comment by ddsjoberg** [comment]
@timtreis I agree, likely not worth another dependency. I would suggest 
1. The source code for the step ribbon function is released with the MIT license (very permissive), so we can just copy it into the package. The downside is that it will then need to be maintained. I haven't looked at the source code yet, but I still this will be the best option. Just credit the source package in the help file?
2. We could add the pammtools pkg as a Suggests and have the CI options be `c("ribbon", "line", "step-ribbon")` and users can use the step ribbon and we check for the installation of pammtools and prompt an install if not already installed. The (big) downside when including many packages in Suggests is ensuring that all R Cmd Checks still pass on older version of R (for example, if pammtools released an update that depended on R 4.0, we have to write additional code to ensure our checks still pass on R 3.5 and 3.6 checks).

**Comment by timtreis** [comment]
I think your 1st suggestion is better. Besides the disadvantages of the second one you already pointed out, we are explicitly being opinionated in `visR` so if we declare somewhere "a survival function is a step function, therefore the CI are also defined in steps" we don't need to be compatible to our previous implementation since the other option is technically incorrect, isn't it?

Also, even if it's under MIT, I'd still give the original author a heads up :D

**Comment by SHAESEN2** [comment]
I already looked at the source code earlier. It is not that easy to copy. Can we contact the original author and see if he would be interested in implementing this in our package as well? or put it on the wishlist?
