### ISSUE TITLE
Create a contributor guide

### ISSUE THREAD

**Issue by SHAESEN2** [openpharma/visR#325]
## Idea

**What is your idea for a new plot/table?**

**Do you have any examples you can share of what it looks like?**

**What potential packages/functions could be used to make this plot?**

**Are you interested to implement this yourself?**

**Comment by SHAESEN2** [comment]
Updating the wiki might be easier.

**Comment by ddsjoberg** [comment]
Update with details
- tibbles vs data.frames
- use of `$` internally
- details on the unit testing framework that has been implemented (sometimes when I do a full check of the package, the entire test file is deleted and re-saved with some changes to the header, I think). As this is a non-standard workflow, details for contributors would be incredibly useful
- add details for expectations of testing for new PRs. the package has amazing testing coverage, but as a new contributor is was difficult to orient myself on how to integrate my own unit tests

**Comment by SHAESEN2** [comment]
Updated Wiki.

**Comment by cschaerfe** [comment]
Updated https://github.com/openpharma/visR/wiki/Contribute with link to https://github.com/openpharma/visR/wiki/Coding-principles
