### ISSUE TITLE
Use CRAN as main 

### ISSUE THREAD

**Issue by SHAESEN2** [openpharma/visR#331]
This is a collaborative project, and sticking with the common practices within the rstats community will foster more collaboration from new contributors. With that in mind, I (I refers to @ddsjoberg) proposes following updates.
- I found it confusing when I first approached the repository to find a production version of the pkg on CRAN, a stable dev version on the main branch, and a dev version.
- Make main/master the default branch
- Use CRAN as production and main branch as dev
- Many functions in the usethis and gert packages use the default branch in important ways that may not jive well with a dev default branch.
- If you keep a non-standard structure, a contributing guide would be helpful outlining what is where and why. For example, when I started my first pull request, I branched from the main branch
There are currently 64 branches in the repo. Implement protocols to avoid accumulation of unneeded and stale branches.

**Comment by bailliem** [comment]
In principle I agree with this proposal @SHAESEN2 .  I'm wondering about the set up to autobuild the documentation in to a seperate repo @epijim. What would the consequences be if we change the set up?

**Comment by ddsjoberg** [comment]
When this occurs, be sure to update the install instructions in `README.Rmd`
![image](https://user-images.githubusercontent.com/26774684/167276262-87a9c2ac-6d4d-4bfd-b60f-8eec5d6e0c48.png)

**Comment by ddsjoberg** [comment]
@bailliem there is a separate repo with documentation? where is that located?

**Comment by bailliem** [comment]
@epijim might need to confirm, but initially this repo was set up for rendered pkgdown documentation https://github.com/openpharma/visR-docs

**Comment by ddsjoberg** [comment]
Ah, ok! @bailliem 

It looks like that repo hasn't been updated in 2 years, and I don't think it's hosting the website.

The visR repo has a GitHub Action to build the pkgdown website automatically and deploys it to the `gh-pages` branch. This is a very typical workflow. https://github.com/openpharma/visR/blob/develop/.github/workflows/pkgdown.yaml

If you go to the repo Settings, select Pages from the menu on the left, you'll be able to see that the website is served from the gh-pages branch. I don't have the permission to view the settings to confirm. But I would bet the setting looks like this:
![image](https://user-images.githubusercontent.com/26774684/167294422-a3683e4e-7dee-4fe1-9265-8038c55e49d8.png)

**Comment by ddsjoberg** [comment]
complete!
