### ISSUE TITLE
README Contents Discussion

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#344]
Hello! I wanted to put out some ideas for some updates to the homepage/README.

The README is a place where someone new comes to learn about the package in a concise way. With that in mind, I think a few changes could be made.
- Add an example of `tableone()`
- Add an example of the attrition figure.
- The figure showing the number of contributors is interesting. But it takes up a lot of space and doesn't a new visitor to the site learn about the package's functionality. An alternative that still exhibits the large contributor base, but also takes up less real-estate on the main page would be the output from `usethis::use_tidy_thanks()`, which lists the username of each contributor and links to their GH page.
- Similarly, showing the number of commits I feel isn't the best use of space on the homepage of the pkg. Also, perhaps in one year's time, many of the existing functions and have been polished and there is far less development going on...the commits figure will look sad 😢 
- There is a badge showing the _amazing_ code coverage. The badge links to a site where you can see the precise coverage of every function. As it's readily available, I don't think the README needs a table showing each file and its corresponding coverage.

I am happy to prepare a pull request that can be reviewed if there is interest.

**Comment by SHAESEN2** [comment]
look at gtsummary readme for an example to print gttable as image

**Comment by ardeeshany** [comment]
Hi @ddsjoberg Did you mean pkgdown's index page or the README, or maybe both? If it's pkgdown, I couldn't find it in this repo. Could you please direct me to the pkgdown files?

**Comment by ddsjoberg** [comment]
The README contents become the home page when the site is built with pkgdown. Is that what you're asking?

**Comment by ardeeshany** [comment]
@ddsjoberg Sorry I was reviewing the develop branch's README, which differed from the main branch's, therefore I assumed the pkgdown could have a separate index.md. Now, it is fine. Thanks.
