### ISSUE TITLE
Error thrown for PR checks with github actions and running covr::codecovr()

### ISSUE THREAD

**Issue by bailliem** [openpharma/visR#350]
#### Issue description

The test coverage check on a PR fails with the following error (below) and more specifically [here for the check output](https://github.com/openpharma/visR/actions/runs/2187487451). It looks like its realted to the interative tutorial - or a test to check if the link to an external data set is still active.

If the issue is related to the test for the external data set for the interactive tutorial, I would propose to move this out for the package development. 

> Run covr::codecov()
> covr::codecov()
> shell: /usr/local/bin/Rscript {0}
> env:
> GITHUB_PAT: ***
> R_LIBS_USER: /home/runner/work/_temp/Library
> TZ: UTC
> R_CHECK_SYSTEM_CLOCK: FALSE
> NOT_CRAN: true
> RSPM: https://packagemanager.rstudio.com/all/__linux__/focal/latest
> Error: Error: Failure in /tmp/RtmpxC7kJD/R_LIBS358b1[2](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:2)e829cb/visR/visR-tests/testthat.Rout.fail
> for (i in seq_along(frames)) { :
> closing unused connection [4](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:4) ([https://raw.githubusercontent.com/vntkumar[8](https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:8)/covid-survival/main/data/final.csv](https://raw.githubusercontent.com/vntkumar%5B8%5D(https://github.com/openpharma/visR/runs/6073591766?check_suite_focus=true#step:5:8)/covid-survival/main/data/final.csv))
> Execution halted
> Execution halted
> Error: Process completed with exit code 1.

**Comment by bailliem** [comment]
Reference to a discussion on this issue in issue #349

**Comment by ddsjoberg** [comment]
This may have resolved on its own. I am not seeing errors thrown on GH Actions now.
For example, check the results here (but only look at the dev branch, not the branches actively being updated).
https://github.com/openpharma/visR/actions/workflows/test-coverage.yaml

**Comment by SHAESEN2** [comment]
It has been resolved!
