### ISSUE TITLE
`test-watchdog_testfiles.R` Issue

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#352]
Hey hey @timtreis !

I wanted to let you know that when I run the unit tests, the `test-watchdog_testfiles.R` file deletes all the unit testing, rewrites then with a new header, but also adds additional spaces between lines every time the tests are run. If I forget to skip these tests locally, each unit test file grows very quickly. Also, the re-writing makes git think I modified every line of every unit testing file. I am not sure the purpose of this file and how it works with the unique unit testing setup of the package.

**Comment by timtreis** [comment]
Hey Daniel, yeah you pretty much perfectly described what it does :D The "delete everything and rewrite" was just the first and easiest solution to implement since otherwise I'd have to check the new generated table of tests (TOT?) against the current one, so that only upon changes, a write would happen.

It's odd and unintended that new blank lines are being added every time, doesn't happen with my Ubuntu so I'll have to investigate.

**Comment by ddsjoberg** [comment]
Thanks @timtreis !

- The biggest issue for me is the adding of blank lines, for sure. When I run `devtools::test()`, it reports the lines where errors occur (which is super helpful for development). But when I got to find the corresponding lines, all the line numbers have changed.
- Regarding the git diff: for reviewers (and for myself when making updates), it's super useful to see what was changed. And having the entire file appear as having been deleted and re-added makes it impossible to review changes in the unit testing files.

If it helps, here's a screengrab of the changes that occur after running the unit tests. You can see on the left, all files have been "modified", and on the right you can see these strange line breaks that are likely rendering as double breaks in RStudio.

If it's an easy fix that is great. Otherwise, I think the benefits of auto-updating the last run date (using the git history we can always look up what, who, and when anything was changed) should be weighed against the two cons above. FYI I am on Windows 10
![image](https://user-images.githubusercontent.com/26774684/164223837-32e11d26-6a20-40b4-9ee7-f7eeed514d77.png)

**Comment by ddsjoberg** [comment]
If it's just a windows issue, we could just add a skip if windows check, `.Platform$OS.type == "windows"` to the test file? Easy work around for the time being

**Comment by timtreis** [comment]
Hey @ddsjoberg, currently in a train without WiFi so I can't push the changes yet. I have now implemented a check for whether the file has actually changed and to only then rewrite it. This would reduce the burden on the reviewer. I don't know if I'll be able to implement a solution (with reasonably little time investment) that doesn't fully rewrite the file but only selectively changes parts. I'll go through the two line issue now and see if its an OS problem 👍

**Comment by ddsjoberg** [comment]
I am cleaning up my open issues, and closing a few
