### ISSUE TITLE
"The package is still experimental and under active development"

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#370]
This appears in the `README`: 
> The package is still experimental and under active development with a current focus on developing a stable API.

Curious where everyone feels where we are on this goal. Hoping I can join Monday's call and can discuss! (putting it here in case I can't)

**Comment by SHAESEN2** [comment]
Put experimental at the function level using lifecycle package, but overall should be removed.

**Comment by bailliem** [comment]
To confirm, lifecycle has to go into imports

**Comment by ddsjoberg** [comment]
> To confirm, lifecycle has to go into imports @bailliem 

it depends on how it's being used. in this case, it can go in Suggests because it's only being used in documentation. I added lifecycle to Suggests in the PR adding the `formula=` argument as an example.

**Comment by bailliem** [comment]
@bailliem  - thanks. I wanted to discuss this today. Good segue
