### ISSUE TITLE
Add `estimate_KM.formula()` method

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#379]
The visualizations for time to event data in visR are amazing and will be used by many people, including those whose data does not follow CDISC conventions. We can do a couple of things to improve their experience, while not taking away from the experience of those working with CDISC data.

One **HUGE** difference between most statistical coding and CDISC is the CNSR column: it's the opposite of what many will expect. TO aid these users, adding a formula method to `estimate_KM()` will allow non-CDISC users to use familiar formula and data syntax, while the CDISC users can continue to utilize the helpful CDISC defaults.

The `estimate_KM.formula()` method will simply parse the formula, and pass the elements to `estamate_KM(data, AVAL, CNSR, strata)`; a simple function adding great usability to many more users.

**Comment by SHAESEN2** [comment]
Our main focus is pharma and working with analysis data standards so I would prefer to keep the behavior as is. I don't see how the addition of a new method would improve the user experience. Perhaps you can make a small example?

**Comment by SHAESEN2** [comment]
Our main focus is pharma and working with analysis data standards so I would prefer to keep the behavior as is. I don't see how the addition of a new method would improve the user experience. Perhaps you can make a small example?

**Comment by ddsjoberg** [comment]
I am suggesting to keep ALL behavior as is, i.e. still focusing on pharma standards. Adding a formula method only improves usability for non-CDISC data. 

> I don't see how the addition of a new method would improve the user experience. 

The formula method is already familiar to every R user who does survival analyses, and the users won't need to learn new syntax. The CDISC format codes the outcome in the opposite way as every other survival analysis method in R. This is dangerous when users are not using CDSIC data!

We would keep the original function un-altered as a data frame method.
```r
estimate_KM.data.frame <- function(data = NULL, strata = NULL, CNSR = "CNSR", AVAL = "AVAL", ...){}
```

And add a formula method, so users have the option to also use the familiar formula syntax
```r
estimate_KM.formula <- function(formula=, data = NULL, ...){}
```

I have a function draft of the update in the `formula_methods` branch

**Comment by SHAESEN2** [comment]
I see. Perhaps for a next CRAN release then? I would prefer to first to get the other issues resolved.

**Comment by ddsjoberg** [comment]
Let's discuss next week. I agree with you about resolving the other issues first. The code to support formula notation is simple and easily integrated. Definitely something we can finish before the CRAN release (which doesn't have a date!).

We could implement with a formula method (as described above). Or we could simple add a formula argument to the existing function. A screenshot of the help files illustrates the proposed changes well.

1. Add a formula method: 
![image](https://user-images.githubusercontent.com/26774684/168188842-bed9db6f-a74f-4f19-90fb-3b8a74ecef98.png)


2. Add a formula argument. The argument defaults to NULL. If users specify it, then the formula is used, rather constructed from the AVAL, CNSR, and strata arguments.
![image](https://user-images.githubusercontent.com/26774684/168186923-7148c061-40c8-4bd0-9e11-352c13f1ad62.png)


Or something like this
![image](https://user-images.githubusercontent.com/26774684/168188450-ad9607cf-c02c-4522-a524-36a958d6ed9d.png)

**Comment by ddsjoberg** [comment]
- implement with formula method @ddsjoberg 
- also look at vignette converting data to CDISC format. Update that code to use formula method. @bailliem
