### ISSUE TITLE
Ask about possibility of contribution

### ISSUE THREAD

**Issue by kawap** [openpharma/visR#4]
I was asked by @epijim if I could contribute in this project and that's why I would ask you about such possibility. @cschaerfe @diego-s  @bailliem  if these functions already initiated like for example:  `vr_plt_kaplan_meier.R` and `vr_sankey.R `are already in progress / during implementation or not? If not and this assignments in comments are not finally set then I would be happy to work on this.  Or maybe do you have any other kind of visualization-functions or other job to do which is still not initiated?

**Comment by cschaerfe** [comment]
Thanks @kawap for reaching out and apologies for the delayed response. Welcome on board!
@diego-s is taking care of vr_plt_kaplan_meier.R, let me check the status of `vr_sankey` and get back to you. Happy to set up a quick call to bring you up to speed!
