### ISSUE TITLE
`README.Rmd` builder GH Workflow

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#401]
There are a few issues with the GitHub Actions Workflow that builds the `README.Rmd` for every push.
1. (An issue we've spoke about before) When the workflow pushes the knitted `README.md` file to the pull request branch, the GitHub Checks get confused. We no longer see the R CMD Check results, the test coverage workflow results, etc. Instead we're presented with a message indicating that we're waiting for the results.

    ![image](https://user-images.githubusercontent.com/26774684/172919741-d18ab341-1efd-469f-8ae5-b8b78dc21f35.png)

2. Because the GH Action checks results are not reported back, we never meet the "Requirement" that the check pass before merging the pull request. This requires us to override the the requirement, nullifying requirement that the checks pass. My guess is that most are not (if any) going into the Actions tab to find the results of each workflow associated with the current PR they are reviewing.
3. The workflow is there to ensure that the README stays up to date. But there is an issue with images created when `README.Rmd` in knit are updated and saved to `~./man/figures/README-****.png`. The images are not being committed and pushed in the workflow. Therefore, the images in the README are only updated when the README is manually knit.
4. The automated knitting has also led to multiple merge conflicts. Not overly difficult to manage, but certainly not a smooth experience.

I agree that an updated README is good to have. I propose we remove the workflow to preserve the R CMD Check results which are more important for review. We can add to the PR checklist that the README is knit before merging to ensure each PR has the most up-to-date readme.

Also, whenever we're ready for a release, the Checklist that is generated from `usethis::use_release_issue()` includes a line for rendering the README to ensure the pkg is submitted with an up-to-date README.

**Comment by bailliem** [comment]
As a temp fix I have disable the build readme action

**Comment by bailliem** [comment]
I agree with the proposal to add a manual build to the checklist
