### ISSUE TITLE
KM figures cut off at ends with `visr(x_ticks=)`

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#402]
When using `visr.survfit(x_ticks=)` to reduce the range of values shown, the curves a cut off early, rather than being zoomed in on. In the example below, the KM curves are cut off, but you can see from the risk table that them are still patients at risk at 10 years and the lines do not appear.

Perhaps we should use coord zoom rather than xlim?

![image](https://user-images.githubusercontent.com/26774684/172972440-7a8ae446-a4b5-403d-a194-b9f526420975.png)

**Comment by timtreis** [comment]
Played around with it hoping for a quick fix and it looks a bit more complex than a 30 min fix. It seems the line after the "drop" is only motivated by the next "drop"

**Comment by ddsjoberg** [comment]
I think if we switch from `xlim` to `coord_cartesian()`, the figure will zoom-in to the specified limits after the graph is constructed, rather than delete data outside the limits then build graph. @timtreis and I agree, not a simple fix!
