### ISSUE TITLE
Why all the prefixes?

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#406]
Hi Team, 

I know there was a decision as some point to add package prefixes throughout. But I struggle to understand where they are expected and why. Let's discuss at an upcoming call.

**Examples in Help Files**
I think I've heard the term "good practices" thrown around regarding the prefixes in the help files. Is the assertion here that loading packages is not good practice? (This would be news to every R programmer I know!) If the argument is that packages need not be loaded/attached, why is there no prefix added to `visR::adtte` ?

Is it about code readability? In many examples, the prefixes certainly make the code more difficult to digest. Taking the first example from the `visr()` function:
```r
km_fit <- survival::survfit(survival::Surv(AVAL, 1-CNSR) ~ TRTP, data = adtte)
```
Most would find the following easier to read
```r
library(survival)
km_fit <- survfit(Surv(AVAL, 1-CNSR) ~ TRTP, data = adtte)
```

I know of no other package that uses its own package name prefix in the examples, and unless there is an amazing reason not to, sticking with the conventions makes it easier for users to digest the material in formats they are familiar with.

**Prefixes inside functions**
The `base::` prefix is commonly found throughout the package. Is there a reason for this?

**Unit Testing**
Every. single. function. from the testthat package has a prefix (thousands of calls to these functions, perhaps). Why is this being done? The unit testing framework attaches the testthat package before the unit tests all run AND 'load all' also attaches them. Again, i've never seen a package that uses the prefixes in unit testing and I've never had to attach the testthat library while performing unit tests.

**Comment by SHAESEN2** [comment]
Not prefixing in the package has caused problems in the past eg the use of filter. Also while developing, I find it easier not to load all the packages that I need while working.

**Comment by ddsjoberg** [comment]
@SHAESEN2 yes, the dplyr::filter vs base::filter is the most annoying tidyverse name conflict!

Have you experimented with `devtools::load_all()`. This function loads all the functions in a package (including non-exported functions), imported functions too? It's a god-send while developing and reviewing. There is a keyboard shortcut for it and a button in the Build tab. Anyway, that's not what this issue is about!


Thanks for the details. Do you have insight on why the visR prefix is used in examples? And why it's not used for the adtte data frame? If removing the prefix in the examples improves readability, it would make sense to not include them there?

**Comment by SHAESEN2** [comment]
In the examples it is also good practice to make sure you are using the current version of the package and not something you have manipulated in your session. If you prefer we can prefix adtte.

**Comment by timtreis** [comment]
Also, if you stray away from the clinical part a bit and use some of the bioconductor packages, half of them redefine most tidyverse names for their specific molecule or nucleic acid of interest. In some projects, I had simultaneously 5 different packages using the `filter` verb.

**Comment by ddsjoberg** [comment]
> In the examples it is also good practice to make sure you are using the current version of the package and not something you have manipulated in your session. 

The examples are for the users not the devs. The prefixes in the examples reduce readability for users, and not including the prefixes is consistent with every other package the users encounter. 
If it's easier for users and consistent with every other package the users will encounter, they' 

> If you prefer we can prefix adtte.

No thanks ;)

> Also, if you stray away from the clinical part a bit and use some of the bioconductor packages, half of them redefine most tidyverse names for their specific molecule or nucleic acid of interest. 

Doesn't seem like removing prefixes for visR functions in the examples, which reduces readability, would be affected by this.

**Comment by ddsjoberg** [comment]
I am cleaning up my open issues, and closing a few
