### ISSUE TITLE
"Run Tests" button for unit tests

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#407]
The RStudio IDE recognizes unit testing files and kindly presents us different buttons to assist with unit test when a unit test file is active. In the screengrab below, you'll see a Run Tests button to run the tests. It's a great feature.

![image](https://user-images.githubusercontent.com/26774684/173345164-07c30d0b-6741-41e7-b5bc-f86c9f27f4e2.png)

But, the roxygen2 comments we keep at the top of each of the unit testing files confuses the IDE and we don't get the added features 

Is there a way to add to keep both the roxygen2 comments and the IDE unit testing features?

**Comment by ddsjoberg** [comment]
I did a bit of testing internally and it is **not** the roxygen comments that is confusing the RStudio IDE...it's the `testthat::` prefix. If the prefix is omitted, the Run Tests button appears and we get all the goodness the IDE offers for unit testing.

**Comment by ddsjoberg** [comment]
@SHAESEN2 i swear i am not on a prefix crusade! 😆 😆 😆 

Removing the `testthat::` prefixes in the unit testing files unlocks the RStudio IDE tools for unit testing, and I think we need to remove them. I 100% thought it was the roxygen comments this entire time.

**Comment by SHAESEN2** [comment]
I prefer the prefixes to be consistent with the package and not to load the testthat package while running interactively.

**Comment by ddsjoberg** [comment]
Had a call with @SHAESEN2 @bailliem today. We can make this update, but it's not a priority and not before the next CRAN release.

**Comment by timtreis** [comment]
We could also flag that as a bug with Rstudio :eyes: It's probably some regex that doesn't trigger for the prefixed one, could maybe be an oversight on their side?

**Comment by ddsjoberg** [comment]
@timtreis submitting an issue to try RStudio ide repo is a great idea. However, I've submitted bugs there before, and it takes a very very long time to make it into the released version of the IDE.

**Comment by ddsjoberg** [comment]
I am cleaning up my open issues, and closing a few
