### ISSUE TITLE
Data Source caption duplicated in DT rendering of Table1

### ISSUE THREAD

**Issue by cschaerfe** [openpharma/visR#41]
The caption at the bottom of a DT-rendered table seems to replicate every time the user interacts with the table (filtering, sorting etc.). 

MRE:
```
adtte %>%
  visR::estimate_KM("TRTP") %>%
  visR::get_pvalue() %>%
  visR::render(title = "P-values", 
               datasource = paste0("Analysis data - time to event"),
               engine = "DT")
```
Then interact with the table.

![image](https://user-images.githubusercontent.com/3072980/78102827-9145c900-73eb-11ea-82f6-c2da705078a4.png)

Likely caused by the caption being added to the DT object in using `drawCallback = DT::JS(source_cap))`
https://github.com/openpharma/visR/blob/68941e71c083dcd6b5ff32c5c892760c0c1d5b4c/R/vr_render_table.R#L81-L88

**Comment by dazim** [comment]
Is this issue still relevant? I'll most likely have some hours to spare over the next couple weeks and this looks quite actionable for getting started :)

**Comment by cschaerfe** [comment]
@dazim Yep, that issue is still relevant. Sorry I didn't see the comment earlier during maternity leave!
