### ISSUE TITLE
Surv_CNSR: "The results of the estimation match between Surv_CNSR and Surv with inverted censoring" fails

### ISSUE THREAD

**Issue by timtreis** [openpharma/visR#413]
#### Issue description

![image](https://user-images.githubusercontent.com/12818242/174405763-4785f168-0f52-415e-863d-bec0e2273bb4.png)

#### Steps to reproduce the issue

The test expects `km1` and `km2` to be equal. They are not
```r
km1 <- adtte %>% visR::estimate_KM(formula = visR::Surv_CNSR() ~ 1)
km2 <- adtte %>% visR::estimate_KM()
```
![image](https://user-images.githubusercontent.com/12818242/174405979-d839f879-b933-4d73-a63c-6bfe579445f5.png)

**Comment by ddsjoberg** [comment]
@timtreis can you run that again in a proper reprex? They are equal on my machine and they passed the unit tests on GH Actions.

``` r
library(visR)
packageVersion("visR")
#> [1] '0.2.0.9011'

adtte %>% estimate_KM(formula = Surv_CNSR() ~ 1)
#> Call: ~survival::survfit(formula = Surv_CNSR() ~ 1, data = data)
#> 
#>        n events median 0.95LCL 0.95UCL
#> [1,] 254    152     51      44      70
adtte %>% estimate_KM()
#> Call: ~survival::survfit(formula = survival::Surv(AVAL, 1 - CNSR) ~ 
#>     1, data = data)
#> 
#>        n events median 0.95LCL 0.95UCL
#> [1,] 254    152     51      44      70
```

<sup>Created on 2022-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by timtreis** [comment]
I'll check in a bit, currently tracing something in the apply_theme function :)

**Comment by timtreis** [comment]
Weird, your exact code results in inequal results at my machine. But if the GH actions agree with you, it must be sth about my session :shrug:
