### ISSUE TITLE
`add_*()` functions as proper ggplot2 geoms?

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#415]
Because we use standard function definitions for the `add_*()` functions to add information to the ggplots, we have to be careful when mixing visR functions with ggplot2 functions.

For example, you can't have a pipe that mixes `%>%` with `+`. If we defined the `add_*()` functions as proper geoms, then we'd be able to seamlessly add ggplot and visR functions.

``` r
library(visR)
packageVersion("visR")
#> [1] '0.2.0.9012'

# this DOES NOT work
adtte %>% 
  estimate_KM(formula = Surv_CNSR() ~ 1) %>%
  visr() +
  ggplot2::scale_y_continuous(labels = scales::percent) %>%
  add_risktable()
#> Error in UseMethod("add_risktable", gg): no applicable method for 'add_risktable' applied to an object of class "c('ScaleContinuousPosition', 'ScaleContinuous', 'Scale', 'ggproto', 'gg')"

# can we make this syntax work, if we make the fns `add_risktable()` a proper ggplot geom?
adtte %>% 
  estimate_KM(formula = Surv_CNSR() ~ 1) %>%
  visr() +
  ggplot2::scale_y_continuous(labels = scales::percent) +
  add_risktable()
#> Scale for 'y' is already present. Adding another scale for 'y', which will
#> replace the existing scale.
#> Error in add_risktable(): argument "gg" is missing, with no default

# we can make the existing implementation work with extra parantheses
(adtte %>% 
  estimate_KM(formula = Surv_CNSR() ~ 1) %>%
  visr() +
  ggplot2::scale_y_continuous(labels = scales::percent)) %>%
  add_risktable()
#> Scale for 'y' is already present. Adding another scale for 'y', which will
#> replace the existing scale.
```

![](https://i.imgur.com/AvvfWGU.png)

<sup>Created on 2022-06-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Read more on extending ggplot here: https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html

**Comment by timtreis** [comment]
From some experimentation ages ago I think this might be a non-trivial thing (although definitely a very good feature). Especially with the risktable, we're breaking forward-compatibility because the table doesn't follow ggplot's idea and is basically just glued onto it. `add_CI` and the like might be easiert

**Comment by ddsjoberg** [comment]
I am cleaning up my open issues, and closing a few
