### ISSUE TITLE
shinyapp.io GH Action Deploy Failed

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#418]
The GitHub Action that deploys to shinyapp.io did not complete successfully. Need to look into the details. cc @timtreis 

See PR https://github.com/openpharma/visR/pull/416

**Comment by SHAESEN2** [comment]
If I understand it correctly, it requires visR but it is not on CRAN anymore :)

**Comment by ddsjoberg** [comment]
I am cleaning up my open issues, and closing a few
