### ISSUE TITLE
Delete unused branches

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#419]
Please review the stale branches and delete the ones you created that are no longer needed.

Stale branches listed here: https://github.com/openpharma/visR/branches/stale
- [x] @ddsjoberg 
- [ ] @timtreis 
- [x] @SHAESEN2 
- [ ] @AlexandraP-21 
- [ ] @bailliem

**Comment by timtreis** [comment]
Some of my old unused branches were partially implemented functions (like plotly support) that we parked in branches before deleting from the `develop` branch. Is there a better solution for this @ddsjoberg ?

**Comment by ddsjoberg** [comment]
@timtreis I think first preference is for these branches to live in an author or contributors fork, but having them in the primary repository certainly is fine.

Every so often, the repo branches can be prined to keep the repo clean and clear of any branches that have become obsolete.

**Comment by ddsjoberg** [comment]
@timtreis so even if GH marks a branch as stale, it's fine to keep. Once you've deleted the truly unneeded branches, feel free to check your name off.

**Comment by ddsjoberg** [comment]
I am cleaning up my open issues, and closing a few
