### ISSUE TITLE
Add CFF file to repo for direct citation from GH

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#422]
When you add a CFF file to the repo, you'll see a cute button so anyone can easily cite the repo. 

https://citation-file-format.github.io/#:~:text=cff%20files%20are%20plain%20text,to%20correctly%20cite%20their%20software.

![image](https://user-images.githubusercontent.com/26774684/174918807-60303356-41cf-42b5-8cd9-953ac05c4366.png)

With that in mind, how do you feel about submitting an article about visR to JOSS at some point?
If we do submit to JOSS, we would also want to add a `inst/CITATION` file to specify how the repo should be referenced (e.g. using the manuscript instead of the BibTex `@Manual` entry. The CITATION file will also direct how the `citation()` results look.

**Comment by SHAESEN2** [comment]
It was something that has been on my mind. I would say, we go for it!

**Comment by ddsjoberg** [comment]
I am cleaning up my open issues, and closing a few
