### ISSUE TITLE
Release visR 0.3.0

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#426]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `git push`
* [ ] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `git push`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by SHAESEN2** [comment]
What did you have in mind for blog post or twitter?

**Comment by SHAESEN2** [comment]
visR 📦 v0.3.0 is now on CRAN.

This cross-industry effort results in beautiful survival plots and aims at replacing survminer on the long run.

Check out the updates here https://cran.r-project.org/web/packages/visR/news/news.html

What do you think?
@ddsjoberg 
@bailliem

**Comment by SHAESEN2** [comment]
Can this be closed since we will not be advertising it?
