### ISSUE TITLE
Readme not fully rendering

### ISSUE THREAD

**Issue by bailliem** [openpharma/visR#435]
The Readme on main has dropped a number of contributors at the bottom of the page. Probably related to a local build of readme.

**Comment by SHAESEN2** [comment]
It is because it lists the contributors to the develop, not the main. Alexandra was added manually because she contributed alot but never got a PR completed.

**Comment by SHAESEN2** [comment]
✓ Resolving timestamp for ref 'v0.3.0'
✓ Looking for contributors from 2022-06-24 to now
✓ Found 1 contributors:
  [&#x0040;bailliem](https://github.com/bailliem).
