### ISSUE TITLE
test-coverage failure

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#441]
The test-coverage GH Action has been failing for a while. It seems to be associated with the connection check for a CSV file that is saved online. https://raw.githubusercontent.com/vntkumar8/covid-survival/main/data/final.csv

Rather than checking for a proper connection, can we just see if the typical import fails `read.csv("https://raw.githubusercontent.com/vntkumar8/covid-survival/main/data/final.csv")` ? Per CRAN policy, we would need to have a  "graceful failure" if there is no internet access. @timtreis do you have thoughts on this? (assuming you wrote this test?)

![image](https://user-images.githubusercontent.com/26774684/178768751-c055dac8-d2d6-4e91-91ef-56eb0314ced3.png)

**Comment by timtreis** [comment]
So the action fails because there is no "what if no internet"? Or is the file not available through the action? We're just using it for the interactive vignette since it's a simple public cohort. It's very small, worst case we can internalise it.

**Comment by ddsjoberg** [comment]
@timtreis i am not sure 100% why it's failing...the message is just something about closing an open connection 🤷🏼‍♂️ 

I think there is likely internet access and not the cause of the issue.

**Comment by ddsjoberg** [comment]
I am cleaning up my open issues, and closing a few
