### ISSUE TITLE
add_CI() gives error: Can't find `stat` called 'stepribbon'

### ISSUE THREAD

**Issue by kawap93** [openpharma/visR#449]
#### Issue description
We use `add_CI()` method in Kaplan Meier Analysis and last changes in newest version  `0.3.0.9003`  broke up this in our dashboard.
In last commit @ddsjoberg has created custom ggproto object `StatStepribbon` and used that in `add_CI()` what cause an error **Can't find `stat` called 'stepribbon'** when visR package is not loaded.  

#### Steps to reproduce the issue

When you will not load `library(visR)` then we can see that:

```r
p <- visR::adtte %>%
  visR::estimate_KM(strata = "SEX") %>%
  visR::visr()

p %>%
visR::add_CI()
```
will cause the error.

#### What's the expected result?

We should be able to use `add_CI()` referring it by `visR::add_CI()` without loading all package. 

#### What's the actual result?

- currently in the code it's like:
```r
gg <- gg +
      ggplot2::geom_ribbon(ggplot2::aes(
        ymin = est.lower,
        ymax = est.upper
      ),
      stat = "stepribbon",
      na.rm = TRUE,
      show.legend = FALSE
      ) +
      ggplot2::scale_fill_manual(values = ggplot2::alpha(strata_colours, alpha))
```
**stat = "stepribbon"** cause a problem.

#### Additional details / screenshot

and I am asking if my pr: https://github.com/openpharma/visR/pull/448 
can solve the problem?

**Comment by bailliem** [comment]
@kawap93 - could you check the current patch resolves the issue? We still need to add additional unit tests on add_CI to account for the addition of step_ribbon in issue #443

**Comment by bailliem** [comment]
close with #450
