### ISSUE TITLE
False error message

### ISSUE THREAD

**Issue by therneau** [openpharma/visR#451]
I have just submitted a new version of the survival package to CRAN, and a part of that process is a check of every reverse dependency --- all 808 of them --- to ensure that my changes have not affected another package.   I am then asked to resolve any issues that arise, before the update is accepted.   I actually pre-check all of these before submission to find any errors on my part, it normally takes a full day or more.

The visR package appears to have a check whose only purpose to raise an error whenever I make a change, i.e., the following code in tests/testthat/test-Surv_CSNR
```r
  # WHEN THIS TEST FAILS, THAT IS OUR SIGNAL THAT {survival} HAS BEEN UPDATED ON CRAN!!
  # AT THAT POINT WE SHOULD DO THE FOLLOWING
  # 1. UPDATE THIS UNIT TEST TO ASSURE THERE IS _NO_ ERROR WITH coxph()
  # 2. ADD A MIN VERSION REQUIREMENT FOR THE {survival} PACKAGE
  #    THIS CAN BE DONE IN TWO WAYS:
  #      1. in the DESCRIPTION file
  #      2. using rlang::check_installed("survival", version = <add required version number>)
  testthat::expect_error(survival::coxph(visR::Surv_CNSR() ~ SEX, data = adtte))
```
Please find another way to track changes to my package; using me as your semaphore is impolite.

Terry Therneau, author of survival

**Comment by ddsjoberg** [comment]
Dear @therneau , Apologies, I included this as a signal to us and unfortunately neglected to consider reverse dependency checks. It's been removed, and again sincere apologies for you needing to investigate the issue.
