### ISSUE TITLE
Correct estimation of the censoring distribution

### ISSUE THREAD

**Issue by therneau** [openpharma/visR#452]
I noticed that this package estimates time to censoring using the "survfit(Surv(time, 1-status))" trick.   If one's goal is simply to compute the median follow-up for a study, this will most often work just fine.   

If a data set has time-dependent covariates, as useful addition is to make code that treats only the last row for a subject as 'censoring'; that is, only reverse the status in the last row for a subject, forcing status==0 in all intermediate rows.   When allowing for Surv(time1, time2, status), however, the code does need to check that each subject starts at time 0;  "median follow-up" is not a well defined idea when there is left truncation.  

A second issue arises when computing inverse probability of censoring weights if there are tied death and censoring times, but I don't think you deal with this.   The survival:rttright function deals with both issues, if you are curious.

**Comment by ddsjoberg** [comment]
Thank you for the note @therneau !

In this case, we're not seeking to estimate the censoring distribution. We often use CDISC data, which comes along with some strict naming and coding conventions. For time to event data, the dataset must be called `ADTTE`, the censoring column must be named `CNSR`, and it must be coded `1 = 'patient censored', 0 = 'patient died'`.

We include `survfit(Surv(time, 1 - status))` to recode the outcome to the format more widely used where the outcome is 1 if observed and 0 if censored.
