### ISSUE TITLE
Default and Custom Color Palettes (`vr_style`)

### ISSUE THREAD

**Issue by cschaerfe** [openpharma/visR#48]
Colors may be a second task to be tackled separately from the theming that is integral to styling the visualisation. There may be some requirements making this a non-trivial task to automate, though, so it'd be great to have a discussion on this prior to implementation.

Some requirements that came up before
- colors should be used sparingly and only where needed to convey message
- colors should be consistent across visualisations  in the report (i.e., the same drug should always have the same color across a series of graphs)
- defaults needed for continuous and discrete variables
- ability to define specific colors for key variable values (e.g., drugs of particular interest, custom colors for factor values, ...)
- depending on use case: use corporate design colors as standard palette (parameterized by company or institution)
- colors should be discernible even if colorblind

To some extent, one could specify default color palettes at the beginning of the (rmarkdown) script using options for, e.g., ggplot2.continuous.colour and ggplot2.continuous.fill, but that would not account for most of the above customizations required for adhering to good graphics principles and our stakeholder requirements.

Does anyone have an idea how to best implement these requirements around colors and styling in the package? I guess we'd need to disentangle what could be meaningful defaults to be set at the document setup phase and what could be customized in a `vr_style_plot` function?

**Comment by mattfidler** [comment]
I have an old function that can pull the color pallet from a powerpoint function, if that would be useful here.

**Comment by cschaerfe** [comment]
Thanks @ddsjoberg, that is indeed quite helpful!

**Comment by cschaerfe** [comment]
Just putting it here so we don't forget. [Thematic](https://rstudio.github.io/thematic/) looks like it could be super useful for some of the styling aspects since it allows to pull in themes from css as well -- e.g., for shiny apps and maybe custom-styled reports (maybe in combination with [bs_theme from bootstraplib](https://rdrr.io/github/rstudio/bootstraplib/man/bs_theme.html))?
