### ISSUE TITLE
Remove bioconductor dependency

### ISSUE THREAD

**Issue by epijim** [openpharma/visR#50]
#### Issue description

We have bioconductor dependencies for the example data - this makes installation difficult I'm getting errors now on R 4.0

See here: #42

**Comment by thomas-neitmann** [comment]
I second this. Apart from issues with installation, CRAN only accepts packages whose dependencies are all on CRAN as well. Thus, keeping the Bioconductor dependencies would be a deal breaker for getting the package on CRAN at one point.

**Comment by epijim** [comment]
I've made the code change - trying to fix some build issues on my laptop, then I'll make a PR.
