### ISSUE TITLE
NA Handling in vr_table_one

### ISSUE THREAD

**Issue by kzalocusky** [openpharma/visR#58]
Greetings!

I'm hoping to use vr_table_one, but some of my values are missing/NA. I run into this error:

Error in quantile.default(x, probs = 0.25) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

If I change the NAs to "missing", as in the example in the doc, it then treats my continuous variable (age) as a categorical, and rather than get mean/median/etc, I get "number of unique values" in the table.

Is there a good workaround for this?

Thanks!
Kelly

**Comment by kentm4** [comment]
I have submitted #62 to address this issue.

**Comment by SHAESEN2** [comment]
Can we close this issue @bailliem ?

**Comment by bailliem** [comment]
Yes, let's close it.
