### ISSUE TITLE
convert render_table into an S3 method

### ISSUE THREAD

**Issue by yonicd** [openpharma/visR#64]
Converting this core package function into an S3 method would:

  - make the package more extendable and accessible to more developers to add on different table engines that they use. 
  - make testing more compartmental and simpler to track since each engine would be self contained.
  - create a simpler way to make `knitr::knit_print` methods to better connect with `knitr` and its methods.

https://github.com/openpharma/visR/blob/b257ad4a01aa5e62a9e61cfdc9e6d0c07cd05d74/R/vr_render_table.R#L19

**Comment by cschaerfe** [comment]
@yonicd great point, thanks for bringing this up!

**Comment by cschaerfe** [comment]
Done in the refactoring step. We now have to S3 functions: `visr` for creating ggplots and `render` for tables
