### ISSUE TITLE
Consolidate vr_utils.R and utilities.R

### ISSUE THREAD

**Issue by cschaerfe** [openpharma/visR#71]
It looks like we have several places where utility functions are defined: minimally R/vr_utils.R and R/utilities.R. Maybe it's good to agree on one single place for this? Happy to be convinced otherwise.

**Comment by SHAESEN2** [comment]
As far as I understood, the vr_utils contain summary functions. Perhaps they should move to get_summary?

**Comment by timtreis** [comment]
Can be closed?

**Comment by cschaerfe** [comment]
They were cleaned up by @rebecca-albrecht . The summary functions in the utils are serving a different purpose, than get_summary, so should be kept separate
