### ISSUE TITLE
vr_summarize and get_summary

### ISSUE THREAD

**Issue by cschaerfe** [openpharma/visR#72]
We have multiple functions creating different kinds of summaries:

- `vr_summarize` and `vr_summarize_tab1` are defined and used in the context of creating a summary table (in vr_utils.R)
- `get_summary` is defined to create a summary of a survfit object

I wonder if we should consolidate these methods or alternatively have more distinct names for them to avoid confusion?

**Comment by SHAESEN2** [comment]
I think all functions were consolidated in pull request #68 . Please let me know if there is something we missed.

**Comment by cschaerfe** [comment]
I think we still have two files - one for summaries of TTE analyses and one for the Table one stuff. At least that's what I'm seeing on the most recent version of develop (after merging the pull request). Could you maybe check if you also have `vr_utils` with the table1 related summary functions?
Not sure how to best consolidate as all functions are needed. Maybe different names? Or, given they are S3 functions, merging could be possible, but maybe a bit counter-intuitive?

**Comment by SHAESEN2** [comment]
Now I see. Good idea, but will not be easy.

**Comment by cschaerfe** [comment]
This has been cleaned up for now, but may need further consideration later
