### ISSUE TITLE
Attrition flow chart in Example Analysis vignette not showing correctly

### ISSUE THREAD

**Issue by cschaerfe** [openpharma/visR#76]
Building the example analysis locally (either running each chunk in the notebook or knitting the full document) in RStudio works fine. Executing the following code results in the flowchart shown in the viewer or RStudio:
```
attrition_flow <- vr_attrition(
  N_array = cohort_attrition$`Remaining N`,
  descriptions = cohort_attrition$Criteria,
  complement_descriptions = complement_descriptions,
  display = F,
  output_path = attrition_chart_fn)
```
And embedding the exported svg in the report also works:
![image](https://user-images.githubusercontent.com/3072980/95435385-cd398800-0952-11eb-80ca-81f9ec7f6a8f.png)

**When building the vignette using `pkgdown::build_articles()`, the image included by `knitr::include_graphics` is broken:**
![image](https://user-images.githubusercontent.com/3072980/95435214-98c5cc00-0952-11eb-992f-5d2cb734f7db.png)

Additionally, when knitting the vignette, it the svg (that is shown in the Viewer when working interactively) is not incorporated as an image, but as text:
![image](https://user-images.githubusercontent.com/3072980/95435152-85b2fc00-0952-11eb-9cad-f8870397ff22.png)

And this **svg returned by the call to `attrition_flow` does not appear at all when building the vignette.** 
![image](https://user-images.githubusercontent.com/3072980/95435480-e93d2980-0952-11eb-9376-4578cb083170.png)

One problem seems to be the file path used in `knitr::include_graphics` does not seem correct in the context of the fully built website. Not sure how to correct for this, though... Does anyone know have any ideas how to fix this problem and show the final flow chart in our vignette on the website?

**Comment by cschaerfe** [comment]
Looks like the main problem of the created fig not showing could be solved by some of the descriptions here: https://pkgdown.r-lib.org/reference/build_articles.html

**Comment by bailliem** [comment]
It looks like it is a problem with the file path, see issue here https://github.com/r-lib/pkgdown/issues/1159

Following the example 
do.call(knitr::include_graphics, list(path = attrition_chart_fn))

This will build ok, but in the html we are pointing to the wrong location and will not be picked up when rendered as the root of the path is the example notebook, not the docs folder. 

One quick work around for now is to write the file to the correct folder then write out the js to render i.e. 

<div class="figure">
<img src="Example_analysis_files/figure-html/attrition_diagram.svg" alt="Attrition Diagram of Lung cohort. Data Source: NCCTG Lung Cancer Dataset (from survival package 3.2.3)"><p class="caption">Attrition Diagram of Lung cohort. Data Source: NCCTG Lung Cancer Dataset (from survival package 3.2.3)</p>
</div>

@cschaerfe  and @SHAESEN2  - ugly but will work. What do you think?

**Comment by bailliem** [comment]
There is a further issue. This path has to exist 
`attrition_chart_fn <- "../docs/articles/Example_analysis_files/figure-html/attrition_diagram.svg" `

but won't if we have a clean build of the site.

**Comment by cschaerfe** [comment]
Obsolete now that we refactored the attrition code to return ggplot objects
