### ISSUE TITLE
[KM Plot] Order of N at risk, censored, events in Risktable does not agree with Morris et al.'s suggestion anymore

### ISSUE THREAD

**Issue by cschaerfe** [openpharma/visR#77]
The guidance from the Kmunicate paper is to arrange n.risk, n.censor and n.events by stratum (see example of previos visR KM implementation)
![image](https://user-images.githubusercontent.com/3072980/95437601-784b4100-0955-11eb-9dce-dd128868e9b5.png)

![image](https://user-images.githubusercontent.com/3072980/95437640-84cf9980-0955-11eb-8985-a486268d535f.png)

With our new API, this ordering does not appear possible anymore:
![image](https://user-images.githubusercontent.com/3072980/95437829-c52f1780-0955-11eb-9c00-7c7dc1dcedd3.png)

I think it would be great to include the option to order the elements of the risk table following the KMunicate guidance, though, given that this was one of the motivators to actually write our own  KM function. Maybe in addition to the more common ordering as implemented in ggsurvplot? What do you think?

**Comment by SHAESEN2** [comment]
I very much like the suggestion of KMunicate. I will see what would be the easiest way to implement this.
Personally, I am not a big fan of the survminer proposal. In my experience it is already a struggle to get the correct labels to fit on the graph, without adding the additional strata.

I will look into a way to toggle between having the strata vs the statlist as grouping.

**Comment by SHAESEN2** [comment]
@cschaerfe 

I have made a proposal in the add_risktable_group branch. It is not yet finished, but the examples run fine to give an idea. Let me know what you think.

**Comment by SHAESEN2** [comment]
Should be fixed with PR #84
