### ISSUE TITLE
KM plot show quantiles

### ISSUE THREAD

**Issue by SHAESEN2** [openpharma/visR#93]
Add drop lines to show quantiles of the KM distribution.

**Comment by SHAESEN2** [comment]
Also allow to add horizontal line for median survival using a wrapper around geom_hline(yintercept=xx,  linetype = xx)

**Comment by timtreis** [comment]
@SHAESEN2 I'll probably have some time during R/Pharma 2021 to implement this, doesn't feel like a lot of work. Do you already have a name in mind? `add_survival_quantiles()' with "half" as the default?

**Comment by timtreis** [comment]
Unsorted ideas:
- lines hitting the x-axis in the colour of the strata?
- horizontal lines solid?

**Comment by SHAESEN2** [comment]
add_quantiles and make an S3 method out of it => add_quantiles uses get_quantiles.
I like the dotted lines you show in the example and the line color as per strata.

**Comment by SHAESEN2** [comment]
I think I prefer a default of dotted lines. I asked @AlexandraP-21  to look into it as well. She has a good eye for those things.

**Comment by AlexandraP-21** [comment]
I took a look at the lines and like them dotted. However, I think that maybe (light) grey (and not black) would be better. The coloring ones I found them a bit confusing and distracting to be honest. Hope this helps!
