### ISSUE TITLE
Install Issues - Dependency on V8

### ISSUE THREAD

**Issue by cschaerfe** [openpharma/visR#94]
When trying to install the package in our analytics environment, users often run into issues with resolving the V8 dependency:
```
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
-----------------------------[ ANTICONF ]-------------------------------
Configuration failed to find the libv8 engine library. Try installing:
 * deb: libv8-dev or libnode-dev (Debian / Ubuntu)
 * rpm: v8-devel (Fedora, EPEL)
 * brew: v8 (OSX)
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
---------------------------[ ERROR MESSAGE ]----------------------------
<stdin>:1:10: fatal error: v8.h: No such file or directory
compilation terminated.
------------------------------------------------------------------------
ERROR: configuration failed for package 'V8'
* removing '/home/reyessia/R/x86_64-pc-linux-gnu-library/4.0/V8'
Error: Failed to install 'visR' from GitHub:
  (converted from warning) installation of package 'V8' had non-zero exit status
```

It can be resolved by following the instructions in the traceback, i.e., installing the corresponding libv8 library in the terminal (not in R, but into the system). 
For ubuntu, apparently also the following worked
`sudo apt install librsvg2-dev`

If I remember correctly, we thought we had removed that dependency in develop a while ago, but it seems to be back both on master and develop. @bailliem, @SHAESEN2 do you know if we need this still?

**Comment by SHAESEN2** [comment]
Never heard of package V8 so feel free to delete.

Op vr 16 okt. 2020 om 17:26 schreef Charlotta <notifications@github.com>:

**Comment by cschaerfe** [comment]
Dependency removed
