### ISSUE TITLE
Refactoring issue

### ISSUE THREAD

**Issue by rebecca-albrecht** [openpharma/visR#96]
Renamed the parameter "groupCols" in the functions to create and render a table_one with "group_cols". However, the html in the docs folder remain unchanged. 

Any idea why?

**Comment by SHAESEN2** [comment]
Can you give a bit more detail? Which branch, which function + parameters did you use, why you expect the docs folder to get updated, ...

**Comment by rebecca-albrecht** [comment]
This was repaired a while back
